# Turns on the test page at http://localhost:8080/graphiql

spring.graphql.graphiql.enabled=true

# Optional. Shows your schema as plain text at /graphql/schema
spring.graphql.schema.printer.enabled=true